
import { FileText, BarChart3, Users, Settings, FileArchive, UploadCloud, ImageIcon, FileUp, Vote, CalendarDays, ClipboardCheck, MessageSquareHeart, UserCheck, PieChart, TableProperties, ArrowLeftRight, Flag, ShieldAlert, BookOpen, UserCircle, History, Images, Activity, ScrollText } from 'lucide-react';

export const dashboardMenuItems = [
  {
    href: '/solicitud-capacitacion',
    label: 'Nueva Solicitud',
    icon: ClipboardCheck,
    description: 'Crea una nueva solicitud de capacitación con firma.',
  },
  {
    href: '/agenda-capacitacion',
    label: 'Agenda',
    icon: CalendarDays,
    description: 'Visualiza el calendario de capacitaciones agendadas.',
  },
  {
    href: '/control-movimiento-maquinas',
    label: 'Control de Movimiento de Máquinas',
    icon: ArrowLeftRight,
    description: 'Registro de salida y devolución de equipos de votación.',
  },
  {
    href: '/denuncia-lacres',
    label: 'Denuncia de Lacres',
    icon: ShieldAlert,
    description: 'Reporte de adulteración de los lacres de seguridad.',
  },
  {
    href: '/informe-movimientos-denuncias',
    label: 'Trazabilidad y Alertas',
    icon: ShieldAlert,
    description: 'Monitor central de movimientos con detección de irregularidades.',
  },
  {
    href: '/informe-divulgador',
    label: 'Informe del Divulgador',
    icon: UserCheck,
    description: 'Control individual de marcaciones por ciudadano (Anexo III).',
  },
  {
    href: '/galeria-capacitaciones',
    label: 'Galería de Evidencias',
    icon: Images,
    description: 'Visualiza las fotografías de respaldo de las capacitaciones.',
  },
  {
    href: '/informe-semanal-puntos-fijos',
    label: 'Informe Semanal (Anexo IV)',
    icon: TableProperties,
    description: 'Resumen semanal de puntos fijos de divulgación.',
  },
  {
    href: '/archivo-capacitaciones',
    label: 'Historial / Archivo',
    icon: History,
    description: 'Consulta de actividades finalizadas y archivadas por jurisdicción.',
  },
  {
    href: '/divulgadores',
    label: 'Directorio Divulgadores',
    icon: UserCircle,
    description: 'Gestiona la lista de personal operativo del CIDEE.',
  },
  {
    href: '/estadisticas-capacitacion',
    label: 'Estadísticas CIDEE',
    icon: PieChart,
    description: 'Análisis de resultados de las encuestas de satisfacción.',
  },
  {
    href: '/encuesta-satisfaccion',
    label: 'Encuesta Satisfacción',
    icon: MessageSquareHeart,
    description: 'Formulario de encuesta sobre el uso de la máquina.',
  },
  {
    href: '/conexiones',
    label: 'Monitoreo de Conexiones',
    icon: Activity,
    description: 'Seguimiento en tiempo real de usuarios activos en el sistema.',
  },
  {
    href: '/auditoria',
    label: 'Auditoría del Sistema',
    icon: ScrollText,
    description: 'Registro cronológico de acciones y movimientos de usuarios.',
  },
  {
    href: '/ficha',
    label: 'Vista de Ficha',
    icon: FileText,
    description: 'Consulta informes detallados e imágenes por distrito.',
  },
  {
    href: '/fotos',
    label: 'Imágenes',
    icon: ImageIcon,
    description: 'Explora y gestiona las imágenes de los registros.',
  },
  {
    href: '/cargar-ficha',
    label: 'Cargar Ficha',
    icon: UploadCloud,
    description: 'Accede a tu distrito asignado para cargar datos.',
  },
  {
    href: '/resumen',
    label: 'Resumen',
    icon: BarChart3,
    description: 'Explora un resumen detallado de los informes.',
  },
  {
    href: '/informe-general',
    label: 'Informe General',
    icon: FileArchive,
    description: 'Genera un PDF consolidado de todos los distritos.',
  },
  {
    href: '/importar-reportes',
    label: 'Importar Reportes',
    icon: FileUp,
    description: 'Importa datos de informes desde un archivo Excel.',
  },
  {
    href: '/importar-locales',
    label: 'Importar Locales',
    icon: FileUp,
    description: 'Importa locales de votación desde un archivo Excel.',
  },
  {
    href: '/importar-partidos',
    label: 'Importar Partidos Políticos',
    icon: Flag,
    description: 'Carga el directorio de partidos y movimientos políticos.',
  },
  {
    href: '/cargar-fotos-locales',
    label: 'Cargar Fotos Locales',
    icon: UploadCloud,
    description: 'Sube un lote de fotos para los locales de votación.',
  },
  {
    href: '/locales-votacion',
    label: 'Locales de Votación',
    icon: Vote,
    description: 'Consulta los locales de votación importados.',
  },
  {
    href: '/users',
    label: 'Usuarios',
    icon: Users,
    description: 'Gestiona los usuarios y sus permisos en el sistema.',
  },
  {
    href: '/settings',
    label: 'Configuración',
    icon: Settings,
    description: 'Importa datos geográficos y configura la aplicación.',
  },
  {
    href: '/documentacion',
    label: 'Documentación del Sistema',
    icon: BookOpen,
    description: 'Manual de usuario, roles, permisos y guía técnica.',
  },
];
